import { Data } from '@angular/router';

export interface CtiCase{
  Adres: string;
  BudzetPlanowany: number;
  Chosen: boolean;
  CzyUzytkownikZlecenia: number;
  DataOstWplaty: Data | string;
  DataPrzedawnienia: Data | string;
  DataPrzedawnieniaAgreg: Data | string;
  DataUmowy: Data | string;
  DataWplywu: Data | string;
  DataWyslaniaWezwania: Data | string;
  DataZakonczenia: Data | string;
  DniPrzedawnienia: number;
  DrzewoId: number;
  DrzewoNazwa: string;
  DrzewoPath: string;
  DrzewoPathRejestr: string;
  DziedzinaPrawaID: number;
  Email: string;
  FaktoringDzienneWynagrodzProc: number;
  FaktoringProcZwrotuKapitalu: number;
  FaktoringWaluta: string;
  FaktoringWalutaDataKursu: Data | string;
  FaktoringWalutaID: number;
  FaktoringWalutaPrzelicznik: number;
  FirmID: number;
  GalazPrawaID: number;
  Id: number;
  Inform__dod_: string;
  IsPrzetermAlarm: number;
  IsPrzetermOstrzezenie: number;
  KRS: string;
  KancelariaId: number;
  Klient: string;
  KlientID: number;
  KlientPelnomocnikId: number;
  KlientReprezentantId: number;
  KolejnoscSplatNagId: number;
  KwotaGlowna: number;
  KwotaGlownaPozostalo: number;
  Login: string;
  NIP: string;
  NaGielda: number;
  NaGieldaLoginTrans: number;
  Naleznosci: number;
  NaleznosciPocz: number;
  NaleznosciPoczPozostalo: number;
  NaleznosciPozostalo: number;
  NaleznosciSadowe: number;
  NazwaKomornik: string;
  NazwaSad: string;
  NrDowodu: string;
  NumerRepertorium: string;
  Odsetki: number;
  OdsetkiPocz: number;
  OdsetkiPoczPozostalo: number;
  OdsetkiPozostalo: number;
  Opis: string;
  OznaczenieSprawy: string;
  PESEL: string;
  Pakiet: string;
  PriorytetId: number;
  Prowadzacy: string;
  ProwadzacyId: number;
  ProwizjaOdWplat: number;
  ProwizjaOdWplatOds: number;
  Przelicznik: number;
  REGON: string;
  ReprezentantStrPrzec: string;
  ReprezentantStrPrzecId: number;
  RezerwaCelowa: number;
  Rezultat: string;
  RezultatID: number;
  RodzajZlecenia: string;
  RodzajZleceniaID: number;
  RolaKlienta: string;
  RolaKlientaID: number;
  RolaStrPrzecID: number;
  RowColor: string;
  Saldo: number;
  SaldoPocz: number;
  ScenariuszId: number;
  SelectionAutoInc: number;
  StanInternal: number;
  StanSprawy: string;
  StanSprawyID: number;
  StopienWykonania: number;
  StrPrzecAdres: string
  StrPrzecAdresKoresp: string;
  StrPrzecID: 55687
  StrPrzecKodPocztowy: string;
  StrPrzecKodPocztowyKoresp: string;
  StrPrzecMiasto: string;
  StrPrzecMiastoKoresp: string;
  StrPrzecPelnomocnik: string;
  StrPrzecPelnomocnikId: number;
  StronaPrzeciwna: string;
  StronaWWW: string;
  SygnKomornik: string;
  SygnSad: string;
  SymbolWlasny: string;
  Telefon: string;
  Telefony: string;
  TrudnoscSprawyId: number;
  TypZlecenia: number;
  UczPostUmowyId: number;
  UserModName: string;
  UserUtwName: string;
  Waluta: string;
  WalutaDataKursu: Data | string;
  WalutaID: number;
  WartoscPrzedmiotuSporu: number;
  WplatySum: number;
  WplatySumNaleznSadowe: number;
  WplatySumPocz: number;
  cDataMod: Data | string;
  cDataOstatniegoKontaktu: Data | string;
  cDataUtw: Data | string;
  cNieRozliczajCzasuPracy: number;
  cRyczaltWyczerpanyKwota: number;
  cUserMod: number;
  cUserUtw: number;
  flgKomornik: boolean;
  flgSad: number;
  flgPrzypisani?: boolean;
}
